// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJjD9UPxNLOPMeHV2uzJOz7NzgKEHl4io',
    appId: '1:130772079120:android:fc55862772a5a230003095',
    messagingSenderId: '130772079120',
    projectId: 'class-pulse-bip',
    storageBucket: 'class-pulse-bip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWiDhKhGo7nI3_padkeyBpRZvOHuMB4Dw',
    appId: '1:130772079120:ios:e52677c5cffa91b9003095',
    messagingSenderId: '130772079120',
    projectId: 'class-pulse-bip',
    storageBucket: 'class-pulse-bip.firebasestorage.app',
    androidClientId: '130772079120-kpail5fibggdg8shmcit2pvchupvi8a3.apps.googleusercontent.com',
    iosClientId: '130772079120-kitr18ohpmvc588ipe6fu971b05s75pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.classroomMood',
  );

}